dist: xenial
sudo: required
language: sh

addons:
  apt:
    packages:
    - libxml2-utils

cache:
    directories:
     - .bazel_cache
     - ~/.bazel_binaries

_linux: &linux
  os: linux
_osx: &osx
  os: osx
  osx_image: xcode10.1
_windows:
  os: windows

###
#
# Want to update/change bazel versions?
#
#
# 1. either
#    - If you're updating the default bazel version, change
#      default_bazel_version in .bazelversion
#    or
#    - If you want to add an additional bazel version to the build
#      matrix, set BAZEL_VERSION=<desired-version> along side
#      TEST_SCRIPT below.
#
# 2. If you need to update the Windows version, adjust
#    the windows specific install code below.
#
###

jobs:
  include:
# Lint
    - stage: test
      <<: *linux
      env: TEST_SCRIPT=test_lint
# Test
    - <<: *linux
      env: TEST_SCRIPT=test_rules_scala USE_BAZEL_VERSION=2.0.0
    - <<: *linux
      env: TEST_SCRIPT=test_reproducibility USE_BAZEL_VERSION=2.0.0
    - <<: *linux
      env: TEST_SCRIPT=test_version USE_BAZEL_VERSION=2.0.0
    - <<: *osx
      env: TEST_SCRIPT=test_rules_scala USE_BAZEL_VERSION=2.0.0
    - <<: *osx
      env: TEST_SCRIPT=test_reproducibility USE_BAZEL_VERSION=2.0.0
    - <<: *osx
      env: TEST_SCRIPT=test_version USE_BAZEL_VERSION=2.0.0

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      choco install jdk8 -params 'installdir=c:\\java8'
      mkdir %USERPROFILE%\bazel
      powershell Invoke-WebRequest https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-windows-amd64.exe -OutFile %USERPROFILE%\bazel\bazel.exe
      set PATH=%PATH%;%USERPROFILE%\bazel
    fi
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
      sudo chmod +x /usr/local/bin/bazel
    fi
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      sudo wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-darwin-amd64
      sudo chmod +x /usr/local/bin/bazel
    fi
    cat .bazelrc.travis >> .bazelrc
    
script:
  - |
    cat .bazelrc.travis >> .bazelrc
    if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
      powershell -Command 'Set-ExecutionPolicy RemoteSigned -scope CurrentUser'
      export JAVA_HOME='c:\\\\java8'
    fi
    bash ./${TEST_SCRIPT}.sh ci
